openapi: 3.0.2
paths:
  beers:
    get:
      operationId: get-beers
      description: Get Beer list
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/beerPagedList'
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty
  customers:
    get:
      operationId: get-customers
      description: Get Customer list
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          description: Get Customer list
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/customerPagedList'
        401:
          description: User is not allowed to retrieve Customer list
        404:
          description: Customer list empty
