openapi: 3.0.2
paths:
  beers:
    get:
      operationId: get-beers
      description: Get Beer list
      parameters:
        - name: pageNumber
          in: query
          description: Page Number
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
            example: 2
        - name: pageSize
          in: query
          description: Page Size
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 25
            example: 25
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                $ref: './Schemas.yaml#/components/schemas/beerPagedList'
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty
  customers:
    get:
      operationId: get-customers
      description: Get Customer list
      parameters:
        - name: pageNumber
          in: query
          description: Page Number
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
            example: 2
        - name: pageSize
          in: query
          description: Page Size
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 25
            example: 25
      responses:
        200:
          description: Get Customer list
          content:
            application/json:
              schema:
                $ref: './Schemas.yaml#/components/schemas/customerPagedList'
        401:
          description: User is not allowed to retrieve Customer list
        404:
          description: Customer list empty
