openapi: 3.0.2
paths:
  beers:
    get:
      operationId: getBeerListV1
      summary: Get Beer list
      description: Get a page of **Beer**s in the system
      tags:
        - beers
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/getBeerList'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/errorEmptyList'
    post:
      operationId: newBeerV1
      summary: New Beer
      description: Create a new **Beer**
      tags:
        - beers
      requestBody:
        $ref: "./Components.yaml#/components/requestBodies/newBeer"
      responses:
        201:
          $ref: './Components.yaml#/components/responses/createdBeer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        409:
          $ref: './Components.yaml#/components/responses/conflictBeer'
  beersBeerId:
    get:
      operationId: getBeerByIdV1
      summary: Get Beer by ID
      description: Retrieve a single **Beer** in the system
      tags:
        - beers
      parameters:
        - $ref: './Components.yaml#/components/parameters/beerId'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/getBeer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundBeer'
    put:
      operationId: updateBeerV1
      summary: Update Beer by ID
      description: Update **Beer** by ID
      tags:
        - beers
      parameters:
        - $ref: './Components.yaml#/components/parameters/beerId'
      requestBody:
        $ref: "./Components.yaml#/components/requestBodies/newBeer"
      responses:
        204:
          $ref: './Components.yaml#/components/responses/updatedBeer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundBeer'
        409:
          $ref: './Components.yaml#/components/responses/conflictBeer'
    delete:
      operationId: deleteBeerV1
      summary: Delete Beer by ID
      description: Delete **Beer** by ID
      tags:
        - beers
      parameters:
        - $ref: './Components.yaml#/components/parameters/beerId'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/deletedBeer'
        400:
          $ref: './Components.yaml#/components/responses/errorIdMissingWrongFormat'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundBeer'
  customers:
    get:
      operationId: getCustomerListV1
      summary: Get Customer list
      description: Get a page of **Customer**s in the system
      tags:
        - customers
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/getCustomerList'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/errorEmptyList'
    post:
      operationId: newCustomerV1
      summary: New Customer
      description: Create a new **Customer**
      tags:
        - customers
      requestBody:
        $ref: "./Components.yaml#/components/requestBodies/newCustomer"
      responses:
        201:
          $ref: './Components.yaml#/components/responses/createdCustomer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        409:
          $ref: './Components.yaml#/components/responses/conflictCustomer'
  customersCustomerId:
    get:
      operationId: getCustomerByIdV1
      summary: Get Customer by ID
      description: Retrieve a single **Customer** in the system
      tags:
        - customers
      parameters:
        - $ref: './Components.yaml#/components/parameters/customerId'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/getCustomer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundCustomer'
    put:
      operationId: updateCustomerV1
      summary: Update Customer by ID
      description: Update **Customer** by ID
      tags:
        - customers
      parameters:
        - $ref: './Components.yaml#/components/parameters/customerId'
      requestBody:
        $ref: "./Components.yaml#/components/requestBodies/newCustomer"
      responses:
        204:
          $ref: './Components.yaml#/components/responses/updatedCustomer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundCustomer'
        409:
          $ref: './Components.yaml#/components/responses/conflictCustomer'
    delete:
      operationId: deleteCustomerV1
      summary: Delete Customer by ID
      description: Delete **Customer** by ID
      tags:
        - customers
      parameters:
        - $ref: './Components.yaml#/components/parameters/customerId'
      responses:
        200:
          $ref: './Components.yaml#/components/responses/deletedCustomer'
        400:
          $ref: './Components.yaml#/components/responses/errorIdMissingWrongFormat'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundCustomer'
  customersCustomerIdOrders:
    post:
      operationId: customerOrderV1
      summary: Customer order by ID
      description: Customer **Order** by customerId
      tags:
        - orders
      parameters:
        - $ref: './Components.yaml#/components/parameters/customerId'
      requestBody:
        $ref: './Components.yaml#/components/requestBodies/addBeerInOrder'
      responses:
        201:
          $ref: './Components.yaml#/components/responses/createdOrder'
        204:
          $ref: './Components.yaml#/components/responses/updatedOrder'
        400:
          $ref: './Components.yaml#/components/responses/unfoundBeer'
        401:
          $ref: './Components.yaml#/components/responses/errorUserUnallowed'
        404:
          $ref: './Components.yaml#/components/responses/unfoundOrder'
      callbacks:
        orderStatusChange:
          ${request.body#/orderStatusCallbackUrl}:
            description: Webhook for order status change notifications
            post:
              requestBody:
                $ref: './Components.yaml#/components/requestBodies/beerOrderUpdated'
              respones:
                204:
                  $ref: './Components.yaml#/components/responses/callbackBeerOrder'