openapi: 3.0.2
paths:
  beers:
    get:
      operationId: get-beers
      description: Get Beer list
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                $ref: './Schemas.yaml#/components/schemas/beerPagedList'
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty
