openapi: 3.0.2
paths:
  /v1/beers:
    get:
      operationId: get-beers
      description: Get Beer list
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                $ref: 'OpenAPI.yaml#/components/schemas/beerList'
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty