openapi: 3.0.2
paths:
  /v1/beers:
    get:
      operationId: get-beers
      description: Get Beer list
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  title: Beer
                  description: Beer Class
                  properties:
                    id:
                      type: string
                      format: uuid
                    style:
                      type: string
                      minLength: 3
                      maxLength: 8
                      enum: [ 'ALE', 'PALE_ALE', 'IPA', 'WHEAT', 'LAGER' ]
                      example: 'LAGER'
                    price:
                      type: number
                      format: float
                      minimum: 0.5
                      example: 5.50
                    quantity:
                      type: integer
                      format: int32
                      minimum: 0
                      example: 150
                    brewery:
                      type: object
                      title: Brewery
                      description: Brewery Class
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                          minLength: 3
                          example: 'Brewery inc.'
                        location:
                          type: object
                          title: Location
                          description: Location Class
                          properties:
                            id:
                              type: string
                              format: uuid
                            city:
                              type: string
                              example: Berlin
                            lat:
                              type: number
                              format: double
                            lon:
                              type: number
                              format: double
                          required: [ id, city ]
                      required: [ id, name ]
                  required: [ id, style, price, quantity ]
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty