openapi: 3.0.2
paths:
  beers:
    get:
      operationId: get-beers
      summary: Get Beer list
      description: Get a page of **Beer**s in the system
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          description: Get Beer list
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/beerPagedList'
        401:
          description: User is not allowed to retrieve Beer list
        404:
          description: Beer list empty
  beersBeerId:
    get:
      operationId: get-beer
      summary: Get Beer by ID
      description: Retrieve a single **Beer** in the system
      parameters:
        - $ref: './Components.yaml#/components/parameters/beerId'
      responses:
        200:
          description: Get Beer from beerId
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/beer'
        401:
          description: User is not allowed to retrieve the Beer
        404:
          description: Beer not found
  customers:
    get:
      operationId: get-customers
      summary: Get Customer list
      description: Get a page of **Customer**s in the system
      parameters:
        - $ref: './Components.yaml#/components/parameters/pageNumber'
        - $ref: './Components.yaml#/components/parameters/pageSize'
      responses:
        200:
          description: Get Customer list
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/customerPagedList'
        401:
          description: User is not allowed to retrieve Customer list
        404:
          description: Customer list empty
  customersCustomerId:
    get:
      operationId: get-customer
      summary: Get Customer by ID
      description: Retrieve a single **Customer** in the system
      parameters:
        - $ref: './Components.yaml#/components/parameters/customerId'
      responses:
        200:
          description: Get Customer from customerId
          content:
            application/json:
              schema:
                $ref: './Components.yaml#/components/schemas/customer'
        401:
          description: User is not allowed to retrieve the Customer
        404:
          description: Customer not found