openapi: 3.0.2
info:
  title: OpenAPI Course - Assignment
  description: OpenAPI Course assignment
  version: 1.0.0
  contact:
    name: Pelat-1
    email: nicolo.rogai@outlook.com
    url: https://Pelat-1.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://example.com/terms/
servers:
  $ref: 'Servers.yaml#/servers'
paths:
  $ref: 'APIs.yaml#/paths'
components:
  schemas:
    beer:
      $ref: 'Schemas.yaml#/components/schemas/beer'
    beerList:
      $ref: 'Schemas.yaml#/components/schemas/beerList'
    brewery:
      $ref: 'Schemas.yaml#/components/schemas/brewery'
    breweryLocation:
      $ref: 'Schemas.yaml#/components/schemas/breweryLocation'
    pageable:
      $ref: 'Schemas.yaml#/components/schemas/pageable'