openapi: 3.0.2
info:
  title: OpenAPI Course - Assignment
  description: OpenAPI Course assignment
  version: 1.0.0
  contact:
    name: Pelat-1
    email: nicolo.rogai@outlook.com
    url: https://Pelat-1.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://example.com/terms/
servers:
  - description: Development Server
    url: https://dev.example.com
  - description: QA Server
    url: https://qa.example.com
  - description: Production Server
    url: https://prod.example.com
paths:
  /v1/beers:
    $ref: './APIs.yaml#/paths/beers'
  /v1/customers:
    $ref: './APIs.yaml#/paths/customers'
components:
  schemas:
    address:
      $ref: './Schemas.yaml#/components/schemas/address'
    beer:
      $ref: './Schemas.yaml#/components/schemas/beer'
    beerList:
      $ref: './Schemas.yaml#/components/schemas/beerList'
    beerPagedList:
      $ref: './Schemas.yaml#/components/schemas/beerPagedList'
    brewery:
      $ref: './Schemas.yaml#/components/schemas/brewery'
    breweryLocation:
      $ref: './Schemas.yaml#/components/schemas/breweryLocation'
    customer:
      $ref: './Schemas.yaml#/components/schemas/customer'
    customerList:
      $ref: './Schemas.yaml#/components/schemas/customerList'
    customerPagedList:
      $ref: './Schemas.yaml#/components/schemas/customerPagedList'
    page:
      $ref: './Schemas.yaml#/components/schemas/page'
    pageable:
      $ref: './Schemas.yaml#/components/schemas/pageable'