openapi: 3.0.3
components:
  schemas:
    beer:
      type: object
      title: Beer
      description: Beer Class
      properties:
        id:
          type: string
          format: uuid
        style:
          type: string
          minLength: 3
          maxLength: 8
          enum: [ 'ALE', 'PALE_ALE', 'IPA', 'WHEAT', 'LAGER' ]
          example: 'LAGER'
        price:
          type: number
          format: float
          minimum: 0.5
          example: 5.50
        quantity:
          type: integer
          format: int32
          minimum: 0
          example: 150
        brewery:
          $ref: '#/components/schemas/brewery'
      required: [ id, style, price, quantity ]
    beerList:
      type: array
      title: BeerList
      description: Beer array
      minItems: 1
      maxItems: 100
      items:
        $ref: '#/components/schemas/beer'
    brewery:
      type: object
      title: Brewery
      description: Brewery Class
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 3
          example: 'Brewery inc.'
        location:
          $ref: '#/components/schemas/breweryLocation'
      required: [ id, name ]
    breweryLocation:
      type: object
      title: BreweryLocation
      description: Location Class
      properties:
        id:
          type: string
          format: uuid
        city:
          type: string
          example: Berlin
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
      required: [ id, city ]