openapi: 3.0.2
servers:
  - description: Development Server
    url: https://dev.example.com
  - description: QA Server
    url: https://qa.example.com
  - description: Production Server
    url: https://prod.example.com